color: sky
fieldLayouts:
  18797a18-b16c-41b0-820f-2af1d0e3d4e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T17:06:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97e0d555-b8c5-41fd-8eed-b683b76b5ca1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T17:09:25+00:00'
            elementCondition: null
            fieldUid: 9cce27e4-04db-4300-b9a0-b0af68269519 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28d34ccc-0245-459e-b304-291065731747
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 643cff9b-2eca-4f38-831e-963abe624252
        userCondition: null
handle: singleImage
hasTitleField: true
icon: image
name: 'Single Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
