defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5ad993f4-0b83-4c47-bb32-5529fd1f0722 # Standard Page
handle: homePage
maxAuthors: 1
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  40e607af-3143-418f-995f-d2fe3e03625f: # react-in-craft
    enabledByDefault: true
    hasUrls: true
    template: home/index.twig
    uriFormat: __home__
type: single
